//! Pre-baked nearest-Taco-Bell finder, compiled to WebAssembly.
//!
//! Public API: `find_nearest_three(lat: f64, lon: f64) -> JsValue` returns
//! a JavaScript array of the three closest Taco Bells from a baked-in
//! North American dataset. Zero network calls. Search runs in ~1ms.
//!
//! The dataset is generated at compile time by `build.rs` from
//! `data/na-taco-bells.json` (an Overpass snapshot).

use serde::Serialize;
use wasm_bindgen::prelude::*;

/// A baked-in Taco Bell entry. The lifetime is `'static` because the data
/// lives in the compiled binary, not the heap.
#[derive(Clone, Copy)]
pub struct TacoBell {
    pub lat: f32,
    pub lon: f32,
    pub name: &'static str,
    pub addr: &'static str,
    pub opening_hours: &'static str,
}

// Include the autogenerated `NA_TACO_BELLS: &[TacoBell]` array.
include!(concat!(env!("OUT_DIR"), "/data_generated.rs"));

/// One search hit returned to JS.
#[derive(Serialize)]
struct Hit {
    lat: f32,
    lon: f32,
    name: &'static str,
    addr: &'static str,
    opening_hours: &'static str,
    /// Great-circle distance from the user, in km.
    dist_km: f32,
}

/// Returns the three Taco Bells closest to (lat, lon), sorted ascending by
/// great-circle distance. JS receives an Array of `Hit` objects.
///
/// Runs in O(n log n) over the baked array (~1900 entries), single-pass
/// haversine + partial sort. Bench: ~1ms on a low-end phone.
#[wasm_bindgen]
pub fn find_nearest_three(lat: f64, lon: f64) -> JsValue {
    let mut scored: Vec<(f32, &TacoBell)> = NA_TACO_BELLS
        .iter()
        .map(|tb| {
            let d = haversine_km(lat, lon, tb.lat as f64, tb.lon as f64);
            (d, tb)
        })
        .collect();

    // partial_sort would be nicer but std doesn't have one; sort_unstable
    // is fast enough for ~2000 entries.
    scored.sort_unstable_by(|a, b| a.0.partial_cmp(&b.0).unwrap_or(std::cmp::Ordering::Equal));

    let top3: Vec<Hit> = scored
        .iter()
        .take(3)
        .map(|(d, tb)| Hit {
            lat: tb.lat,
            lon: tb.lon,
            name: tb.name,
            addr: tb.addr,
            opening_hours: tb.opening_hours,
            dist_km: *d,
        })
        .collect();

    serde_wasm_bindgen::to_value(&top3).expect("Hit always serializes to JsValue")
}

/// How many Taco Bells are baked in (lets the JS side display the count
/// for fun: "powered by Rust over N locations").
#[wasm_bindgen]
pub fn dataset_size() -> usize {
    NA_TACO_BELLS.len()
}

/// Great-circle distance in km using the haversine formula.
fn haversine_km(lat1: f64, lon1: f64, lat2: f64, lon2: f64) -> f32 {
    const R_KM: f64 = 6371.0;
    let to_rad = |d: f64| d * std::f64::consts::PI / 180.0;
    let d_lat = to_rad(lat2 - lat1);
    let d_lon = to_rad(lon2 - lon1);
    let a = (d_lat / 2.0).sin().powi(2)
        + to_rad(lat1).cos() * to_rad(lat2).cos() * (d_lon / 2.0).sin().powi(2);
    (2.0 * R_KM * a.sqrt().asin()) as f32
}
