//! Build script — composes the baked Taco Bell array from two sources:
//!
//!   1. `data/canadian-stores.json` — scraped from `tacobell.ca`'s official
//!      store locator (~181 stores). Authoritative for Canada.
//!   2. `data/na-taco-bells.json` — Overpass API snapshot of OSM tags
//!      across the NA bounding box. Better coverage of US, but contains
//!      ghost stores in Canada (closures OSM hasn't reflected).
//!
//! Strategy: Canadian-official goes in first. Then we add OSM entries,
//! skipping any whose coordinates fall within ~250 m of a store we've
//! already added (those are duplicates captured by both sources).
//!
//! Output: `$OUT_DIR/data_generated.rs` containing a `NA_TACO_BELLS` static
//! array literal, `include!`d from `src/lib.rs`.

use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::PathBuf;

use serde::Deserialize;

// ────────────────────────────────────────────────────────────────
// Input schemas
// ────────────────────────────────────────────────────────────────

#[derive(Deserialize)]
struct OverpassResponse {
    elements: Vec<OverpassElement>,
}

#[derive(Deserialize)]
struct OverpassElement {
    #[serde(default)]
    lat: Option<f64>,
    #[serde(default)]
    lon: Option<f64>,
    #[serde(default)]
    tags: Option<HashMap<String, String>>,
}

#[derive(Deserialize)]
struct CanadianStore {
    lat: f64,
    lon: f64,
    #[serde(default)]
    name: String,
    addr: String,
    #[serde(default)]
    opening_hours: String,
}

// ────────────────────────────────────────────────────────────────

fn main() {
    println!("cargo:rerun-if-changed=data/na-taco-bells.json");
    println!("cargo:rerun-if-changed=data/canadian-stores.json");
    println!("cargo:rerun-if-changed=build.rs");

    // (lat, lon, name, addr, opening_hours)
    let mut entries: Vec<(f32, f32, String, String, String)> = Vec::new();

    // 1) Canadian official — load first so they take priority on dedup
    let n_canada = load_canadian(&mut entries);

    // 2) OSM data — skip any node within 250 m of something we already added
    let n_osm_added = load_osm(&mut entries);

    println!(
        "cargo:warning=baked {} entries ({} Canadian official + {} OSM US/Mexico after dedup)",
        entries.len(),
        n_canada,
        n_osm_added,
    );

    let mut out = String::new();
    out.push_str("// AUTOGENERATED by build.rs — do not edit by hand.\n");
    out.push_str("// Sources:\n");
    out.push_str("//   - data/canadian-stores.json (tacobell.ca official scrape — authoritative for Canada)\n");
    out.push_str("//   - data/na-taco-bells.json (OSM Overpass snapshot — US + Mexico)\n");
    out.push_str(&format!("// Total: {} stores\n\n", entries.len()));
    out.push_str("pub static NA_TACO_BELLS: &[TacoBell] = &[\n");
    for (lat, lon, name, addr, hours) in &entries {
        // {:?} on strings → Rust-escaped string literal
        out.push_str(&format!(
            "    TacoBell {{ lat: {:.6}, lon: {:.6}, name: {:?}, addr: {:?}, opening_hours: {:?} }},\n",
            lat, lon, name, addr, hours
        ));
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR unset (cargo bug?)");
    let dest = PathBuf::from(&out_dir).join("data_generated.rs");
    fs::write(&dest, &out).expect("failed to write generated data file");
}

fn load_canadian(out: &mut Vec<(f32, f32, String, String, String)>) -> usize {
    let raw = match fs::read_to_string("data/canadian-stores.json") {
        Ok(s) => s,
        Err(_) => {
            println!("cargo:warning=data/canadian-stores.json not found — skipping Canadian official data. Run scrape-canada.py to generate.");
            return 0;
        }
    };
    let stores: Vec<CanadianStore> = serde_json::from_str(&raw)
        .expect("data/canadian-stores.json is not valid JSON");

    let n = stores.len();
    for s in stores {
        out.push((s.lat as f32, s.lon as f32, s.name, s.addr, s.opening_hours));
    }
    n
}

fn load_osm(out: &mut Vec<(f32, f32, String, String, String)>) -> usize {
    let raw = fs::read_to_string("data/na-taco-bells.json")
        .expect("data/na-taco-bells.json is missing — run the Overpass fetch (see README)");
    let parsed: OverpassResponse =
        serde_json::from_str(&raw).expect("data/na-taco-bells.json is not valid JSON");

    let mut added = 0;
    let mut skipped_dupes = 0;

    'outer: for el in parsed.elements {
        let (Some(lat), Some(lon)) = (el.lat, el.lon) else {
            continue;
        };
        let lat32 = lat as f32;
        let lon32 = lon as f32;

        // Dedup: skip if within ~250 m of any already-added store. (250 m
        // is a generous radius for "same store" — two real Taco Bells are
        // almost never that close.)
        for (existing_lat, existing_lon, _, _, _) in out.iter() {
            if hav_km(lat, lon, *existing_lat as f64, *existing_lon as f64) < 0.25 {
                skipped_dupes += 1;
                continue 'outer;
            }
        }

        let tags = el.tags.unwrap_or_default();
        let name = tags
            .get("name")
            .cloned()
            .unwrap_or_else(|| "Taco Bell".to_string());

        let housenumber = tags.get("addr:housenumber").map(String::as_str).unwrap_or("");
        let street = tags.get("addr:street").map(String::as_str).unwrap_or("");
        let city = tags.get("addr:city").map(String::as_str).unwrap_or("");
        let addr = match (!housenumber.is_empty(), !street.is_empty(), !city.is_empty()) {
            (true, true, true)   => format!("{} {}, {}", housenumber, street, city),
            (true, true, false)  => format!("{} {}", housenumber, street),
            (false, true, true)  => format!("{}, {}", street, city),
            (false, true, false) => street.to_string(),
            (false, false, true) => city.to_string(),
            _                    => String::new(),
        };

        let opening_hours = tags.get("opening_hours").cloned().unwrap_or_default();

        out.push((lat32, lon32, name, addr, opening_hours));
        added += 1;
    }

    if skipped_dupes > 0 {
        println!("cargo:warning=skipped {} OSM entries as duplicates of Canadian-official stores", skipped_dupes);
    }
    added
}

/// Haversine distance, km.
fn hav_km(lat1: f64, lon1: f64, lat2: f64, lon2: f64) -> f64 {
    const R: f64 = 6371.0;
    let to_rad = |d: f64| d * std::f64::consts::PI / 180.0;
    let d_lat = to_rad(lat2 - lat1);
    let d_lon = to_rad(lon2 - lon1);
    let a = (d_lat / 2.0).sin().powi(2)
        + to_rad(lat1).cos() * to_rad(lat2).cos() * (d_lon / 2.0).sin().powi(2);
    2.0 * R * a.sqrt().asin()
}
