//! Build script — reads `data/na-taco-bells.json` (an Overpass API snapshot)
//! and emits `$OUT_DIR/data_generated.rs` containing a `NA_TACO_BELLS` static
//! array literal. The generated file is `include!`d from `src/lib.rs`.
//!
//! Refresh the JSON file by re-running the Overpass query (see README) and
//! re-running `wasm-pack build`.

use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::PathBuf;

use serde::Deserialize;

#[derive(Deserialize)]
struct OverpassResponse {
    elements: Vec<OverpassElement>,
}

#[derive(Deserialize)]
struct OverpassElement {
    #[serde(default)]
    lat: Option<f64>,
    #[serde(default)]
    lon: Option<f64>,
    #[serde(default)]
    tags: Option<HashMap<String, String>>,
}

fn main() {
    println!("cargo:rerun-if-changed=data/na-taco-bells.json");
    println!("cargo:rerun-if-changed=build.rs");

    let raw = fs::read_to_string("data/na-taco-bells.json")
        .expect("data/na-taco-bells.json is missing — run the Overpass fetch (see README)");
    let parsed: OverpassResponse =
        serde_json::from_str(&raw).expect("data/na-taco-bells.json is not valid JSON");

    let mut entries: Vec<(f32, f32, String, String, String)> = Vec::new();
    for el in parsed.elements {
        let (Some(lat), Some(lon)) = (el.lat, el.lon) else {
            continue;
        };
        let tags = el.tags.unwrap_or_default();
        let name = tags
            .get("name")
            .cloned()
            .unwrap_or_else(|| "Taco Bell".to_string());

        // Compose a display address from whichever OSM tags are present.
        let housenumber = tags.get("addr:housenumber").map(String::as_str).unwrap_or("");
        let street = tags.get("addr:street").map(String::as_str).unwrap_or("");
        let city = tags.get("addr:city").map(String::as_str).unwrap_or("");
        let addr = match (
            !housenumber.is_empty(),
            !street.is_empty(),
            !city.is_empty(),
        ) {
            (true, true, true)   => format!("{} {}, {}", housenumber, street, city),
            (true, true, false)  => format!("{} {}", housenumber, street),
            (false, true, true)  => format!("{}, {}", street, city),
            (false, true, false) => street.to_string(),
            (false, false, true) => city.to_string(),
            _                    => String::new(),
        };

        let opening_hours = tags
            .get("opening_hours")
            .cloned()
            .unwrap_or_default();

        entries.push((lat as f32, lon as f32, name, addr, opening_hours));
    }

    let mut out = String::new();
    out.push_str("// AUTOGENERATED by build.rs — do not edit by hand.\n");
    out.push_str("// Source: data/na-taco-bells.json (Overpass API snapshot)\n");
    out.push_str(&format!("// Entry count: {}\n\n", entries.len()));
    out.push_str(&format!(
        "pub static NA_TACO_BELLS: &[TacoBell] = &[\n"
    ));
    for (lat, lon, name, addr, hours) in &entries {
        // Use `{:?}` for strings so Rust string-escapes special chars correctly.
        out.push_str(&format!(
            "    TacoBell {{ lat: {:.6}, lon: {:.6}, name: {:?}, addr: {:?}, opening_hours: {:?} }},\n",
            lat, lon, name, addr, hours
        ));
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR unset (cargo bug?)");
    let dest = PathBuf::from(&out_dir).join("data_generated.rs");
    fs::write(&dest, &out).expect("failed to write generated data file");

    println!("cargo:warning=baked {} Taco Bell entries into the WASM", entries.len());
}
